#pragma once

#define IOCTL_PID_LEVEL_UP_DEV	0x8000
#define IOCTL_PID_HIDE_ME_BABY_DEV	0x8001


#define IOCTL_PID_LEVEL_UP		CTL_CODE(IOCTL_PID_LEVEL_UP_DEV, 0x800, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_PID_HIDE_ME_BABY		CTL_CODE(IOCTL_PID_HIDE_ME_BABY_DEV, 0x800, METHOD_NEITHER, FILE_ANY_ACCESS)